language: cpp
compiler:
  - clang
# before_install:
#   - sudo apt-get update
#   - sudo apt-get install libgtest-dev
before_script:
 - pwd
 - cd samples/STL/
 - pwd
 - which sh
script: sh ./.travis_build.sh
branches:
  only:
    - develop
notifications:
  recipients:
    - mkhan3189@gmail.com
  email:
    on_success: change
    on_failure: always
rvm:
  - 9.00
